### ISSUE TITLE
New Logo Design For Keystore Ultimate

### ISSUE THREAD

**Issue by zularizal** [leonardoxh/keystore-ultimate#5]
Hi, I am a graphic designer, I want to help others in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons and It's free. Do you want it?

**Comment by leonardoxh** [comment]
Sounds really good, I'll appreciate it

**Comment by zularizal** [comment]
Hi, I've designed 3 pieces of logo, what do you think?
Do you want something changed? or which type do you like below?

![logo](https://user-images.githubusercontent.com/38547278/40761276-19841eb2-64c5-11e8-8446-ae44adee746c.png)

**Comment by leonardoxh** [comment]
I love the middle green one as we say here on Netherlands SUPER!

**Comment by zularizal** [comment]
How about this? Do you approve of it

![2](https://user-images.githubusercontent.com/38547278/40775804-2affe512-64f3-11e8-8bfe-3316e8d876ba.png)

**Comment by leonardoxh** [comment]
Awesome

**Comment by zularizal** [comment]
Hi @leonardoxh , I've uploaded logo and icon files to the drive. check this link
https://drive.google.com/open?id=1f4CvU3Hq3rnhrH3wvf94Um7CMZ8lRKHZ

And I have also sent a pull request for you, check #7

**Comment by leonardoxh** [comment]
Wow man this is dam hot, thank you very much

**Comment by leonardoxh** [comment]
PR #7 merged :-)
